.gitignore, package.json, src/components/PO/PO.js, src/components/PO/POForm.js, src/routes/Main.js, test/ui-testing/demo.js
Removes unnecessary `babel` packages and upgrades `eslint-config-stripes`.
Related to https://github.com/folio-org/ui-vendors/pull/41.
ESLint picked up a lot of missing imports? I don't see these files in the repo. Not sure what's going on there:
```
/ui-receiving/src/components/Panes/Panes.js
6:20  error  Unable to resolve path to module '../POLine/POLine'  import/no-unresolved
/ui-receiving/src/components/PO/PO.js
6:30  error  Unable to resolve path to module '../FundDistribution'  import/no-unresolved
7:25  error  Unable to resolve path to module '../LineListing'       import/no-unresolved
8:31  error  Unable to resolve path to module '../PODetails'         import/no-unresolved
9:29  error  Unable to resolve path to module '../Summary'           import/no-unresolved
10:29  error …
```
=>  Clean up dependencies

CHANGELOG.md, src/TitleReceive/TitleReceiveList.js, src/TitleUnreceive/TitleUnreceiveList.js
Caption not displayed when receiving or undeceiving pieces
https://issues.folio.org/browse/UIREC-61
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIREC-61 Caption not displayed when receiving or undeceiving pieces

CHANGELOG.md, src/TitleForm/TitleForm.js
Save & close button should be disabled until all required fields have values entered
https://issues.folio.org/browse/UIREC-49 …
=> UIREC-49 Save & close button should be disabled

CHANGELOG.md, package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UIREC-136
=> UIREC-136: Update circulation interface dependency to support v11

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UIREC-194
=> UIREC-194: Also support `circulation` `12.0`

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UIREC-195
=> UIREC-195: Also support circulation 13.0

CHANGELOG.md, package.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
ui-receiving uses the holdings-storage interface only, not the other two interfaces.
ui-receiving is not affected because the incompatible change is in the DELETE all APIs only that is not used by ui-receiving.
Only the okapiInterfaces need to be expanded in package.json.
=> UIREC-242: Support holdings-storage 6.0 in okapiInterfaces

CHANGELOG.md, package.json
Add version 12.0 to the list of supported inventory interface versions.
DELETE /inventory/instances and DELETE /inventory/items have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-receiving doesn't use these two DELETE APIs therefore no code change is needed.
Fix holdings-storage 6.0 line in CHANGELOG.
=> UIREC-243: Support inventory 12.0 in okapiInterfaces

CHANGELOG.md, src/TitleDetails/AddPieceModal/AddPieceModalContainer.js, src/common/hooks/useQuickReceive.js, src/common/hooks/useQuickReceive.test.js
https://issues.folio.org/browse/UIREC-261
Quick receive action causes extra holding creation, when a new holding location was created for a corresponding piece.
Quick receive action includes the following steps:
1. create (or update) piece (POST (or PUT) /orders/pieces);
2. receive piece (POST /orders/check-in);
As a PUT request does not return any data, currently for the second step initial piece values (from the UI form) are used instead of updated piece data. That might cause extra holdings creation.
Therefore updated piece should be retrieved before receiving.
If there are breaking changes, …
=> UIREC-261 Extra holding appears when creating new holding for already existing location during 'Quick receive'

CHANGELOG.md, package.json, src/ReceivingList/ReceivingList.test.js
Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UIREC-270
=> UIREC-270: Also support circulation 14.0

CHANGELOG.md, package.json
Use plugins compatible with the requested version of stripes (v9).
Refs [UIREC-290](https://issues.folio.org/browse/UIREC-290)
=> UIREC-290 bump optional plugins to compatible versions

CHANGELOG.md, package.json, src/TitleDetails/AddPieceModal/AddPieceModal.js, src/TitleDetails/AddPieceModal/AddPieceModal.test.js
https://issues.folio.org/browse/UIREC-294
When a holding of a piece changes, a check is made to see if the current holding has connections with other items and/or pieces. The absence of links to the current holding implies a proposal to the user to delete or keep this holding. However, it may already have been deleted (as evidenced by the "invalid reference" label), so making additional checks to ensure that it will be abandoned is meaningless.
Check if a holding exists before analyzing if it will be abandoned after changing a piece holding.
https://github.com/folio-org/ui-receiving/assets/88109087/b38e8d2b-9396-4191-85ac-ca8ca41006c9
- …
=> UIREC-294 Check if a holding exists during the abandonment check

CHANGELOG.md, src/TitleReceive/TitleReceiveList.js, src/common/hooks/useReceive.js, src/common/utils/getDehydratedPiece.js, src/common/utils/getHydratedPieces.js, translations/ui-receiving/en.json
The accession number field needs to be included in the “receive all view” table. The accession number field in receive all view has the same behavior as the call number field and item barcode field. See https://issues.folio.org/browse/UIREC-285 for more details.
Requires changes to https://github.com/folio-org/mod-orders as well. [PR#784](https://github.com/folio-org/mod-orders/pull/784)
- …
=> UIREC-285 Include Accession number field in receive all view

CHANGELOG.md, src/TitleDetails/TitleDetails.js, src/TitleDetails/TitleInformation/TitleInformation.js, src/TitleDetails/TitleInformation/TitleInformation.test.js, src/TitleForm/TitleForm.js, src/TitleForm/TitleForm.test.js, translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-288
Add components for viewing and editing the "Claiming active" and "Claiming interval" fields in PO Line details.
https://github.com/folio-org/ui-receiving/assets/88109087/f744a01c-75ab-468a-90c9-4f7d7bcfde9e
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIREC-288 Display and edit claiming active and interval fields in receiving title

CHANGELOG.md, src/TitleDetails/TitleDetailsContainer.js
https://issues.folio.org/browse/UIREC-298
Some queries triggered by UI do not use DB indexes during Get Order/Get Po Line/ Open Oder/ Receive order flow. Need to optimize them to improve performance.
```
13:46:36 [243501/orders;191747/orders-storage] [diku] [c88a8880-f8ec-55c5-a808-14cfb0744108] [mod_orders_storage] WARN  CQL2PgJSON           Doing FT search without index for pieces.jsonb->>'receivingStatus', CQL >>> SQL: receivingStatus = Received >>> get_tsvector(f_unaccent(pieces.jsonb->>'receivingStatus')) @@ tsquery_phrase(f_unaccent('Received')) 
```
Use == instead of = to not use full text search index.
- Does this introduce …
=> UIREC-298 Optimize pieces query to improve performance

CHANGELOG.md, src/TitleDetails/AddPieceModal/AddPieceModal.js, src/TitleDetails/AddPieceModal/AddPieceModal.test.js, src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.css, src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js, src/TitleDetails/AddPieceModal/ModalActionButtons/constants.js, src/TitleDetails/AddPieceModal/ModalActionButtons/utils.test.js, translations/ui-receiving/en.json
[UIREC-292](https://issues.folio.org/browse/UIREC-292) -  set claiming workflow statuses for single piece
https://github.com/folio-org/ui-receiving/assets/116072773/ab9782ad-57b5-4aa7-aba3-bccbc189de78
- https://issues.folio.org/browse/UIOR-1152
- https://issues.folio.org/browse/UIOR-1160
Ideally all of the PRs involved in breaking changes would be merged …
=> UIREC-292: set claiming workflow statuses for single piece

CHANGELOG.md, package.json, src/TitleForm/TitleForm.js, translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-295
Add `<AcqUnitsField />` to the title from and introduce permission sets to assign and manage acq units.
https://github.com/folio-org/ui-receiving/assets/88109087/c70a7958-0a26-402a-ad7b-a710d0fe6e57
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIREC-295 Add the 'Acquisition units' field to the receiving title form

src/TitleDetails/SendClaimModal/SendClaimModal.js
https://issues.folio.org/browse/UIREC-304
When the internal/external note field is cleared on the "Send claim" dialog modal it should update piece fields.
Override the default behavior of converting `''` to `undefined` by passing an identity function.
[Final form docs](https://final-form.org/docs/react-final-form/types/FieldProps#parse)
https://github.com/folio-org/ui-receiving/assets/88109087/67c33281-a600-46a2-bd3e-d5e56dac9c2f …
=> UIREC-304 Set field value as an empty string on the field clear

src/TitleDetails/AddPieceModal/AddPieceModal.js, src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js, src/TitleDetails/AddPieceModal/ModalActionButtons/constants.js, src/TitleDetails/AddPieceModal/ModalActionButtons/utils.test.js, src/TitleDetails/TitleDetails.js, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js
https://issues.folio.org/browse/UIREC-292?focusedCommentId=200172&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-200172
Save actions are expected to be disabled until a user makes any changes to the existing piece.
Make it possible to specify separate actions as disabled.
https://github.com/folio-org/ui-receiving/assets/88109087/a5f1e544-f686-42d9-b56a-b788847c6a30
- Are the JIRAs under active …
=> UIREC-292 Provide independent 'disabled' status for piece actions

CHANGELOG.md, package.json, src/common/constants/api.js, src/common/hooks/usePiecesExpect/usePiecesExpect.js, src/common/hooks/usePiecesExpect/usePiecesExpect.test.js
https://issues.folio.org/browse/UIREC-307
Use "expect" API to update pieces statuses.
https://github.com/folio-org/ui-receiving/assets/88109087/82e987a4-b3fa-4b80-a59d-badc9070eb28
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIREC-307 Expect "Unreceivable" pieces on the full screen form

CHANGELOG.md, src/TitleDetails/AddPieceModal/ReceivingStatusChangeLog/ReceivingStatusChangeLog.js, translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-312 …
=> UIREC-312 Add support of new Action Date column to Piece Status change history

CHANGELOG.md, package.json, src/ReceivingList/ExportSettingsModal/constants.js, src/ReceivingList/ExportSettingsModal/utils/createExportReport.js, src/ReceivingList/ExportSettingsModal/utils/createExportReport.test.js, src/ReceivingList/ExportSettingsModal/utils/getExportFields.test.js, src/TitleDetails/AddPieceModal/AddPieceModal.js, src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js, src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js, src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js, src/TitleDetails/constants.js, src/TitleExpect/TitleExpectList.test.js, src/TitleExpect/constants.js, src/TitleReceive/TitleReceiveList.js, src/TitleReceive/useFieldArrowNavigation.test.js, src/TitleUnreceive/TitleUnreceiveList.js, src/common/hooks/usePaginatedPieces/searchConfigs.js, src/common/hooks/usePaginatedPieces/searchConfigs.test.js, src/common/hooks/usePieceMutator.test.js, src/common/hooks/useQuickReceive.test.js, src/common/hooks/useReceive.js, src/common/hooks/useReceive.test.js, src/common/utils/receive.js, translations/ui-receiving/en.json
[UIREC-316](https://issues.folio.org/browse/UIREC-316) -  bump interfaces for `pieces` (3.0) and `receiving` (2.0) and change field name of "Caption" to Display summary
https://github.com/folio-org/ui-receiving/assets/116072773/bbe30edf-81e1-4270-8b3b-f765cf89ea97
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UIREC-316: bump interfaces for `pieces` (3.0) and `receiving` (2.0) and change field name "Caption" to "Display summary"

CHANGELOG.md, src/TitleDetails/TitleDetailsContainer.js, src/TitleUnreceive/TitleUnreceiveContainer.js, src/common/constants/errorCodes.js, src/common/utils/handleCommonErrors.js, src/common/utils/handleCommonErrors.test.js, src/common/utils/handleReceiveErrorResponse.js, src/common/utils/handleReceiveErrorResponse.test.js, translations/ui-receiving/en.json
[UIREC-275](https://issues.folio.org/browse/UIREC-275) - UIREC-275: support error codes for pieces receive and unreceive actions
https://github.com/folio-org/ui-receiving/assets/116072773/5652dafa-943d-486a-ba5c-e7adc48bcac7 …
=> UIREC-275: support error codes for pieces receive and unreceive actions

CHANGELOG.md, src/TitleReceive/TitleReceiveContainer.js
https://folio-org.atlassian.net/browse/UIREC-337
Update query to support all "expectable" statuses
https://github.com/folio-org/ui-receiving/assets/88109087/13bbaff8-31ed-4744-8e3f-a2d4e7a8c943
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIREC-337 Correct the query used to fetch pieces on the receiving full-screen page

CHANGELOG.md, package.json, src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
https://folio-org.atlassian.net/browse/UIREC-358
Since the filter is now a multi-select, it requires passing the current value of the filter (which is an array), not just one element from it.
Should be merged after:
- https://github.com/folio-org/stripes-acq-components/pull/775
https://github.com/folio-org/ui-receiving/assets/88109087/b4cc452d-da27-4c59-b16d-1ce380723f8b
- Do PRs exist for …
=> UIREC-358 Adjust the location filter to support filtering of receiving titles by multiple PO line locations or holdings

package.json, src/TitleDetails/POLDetails/POLDetails.js, src/TitleDetails/TitleDetails.js
[UIREC-268:](https://folio-org.atlassian.net/browse/UIREC-268?focusedCommentId=214069) add missing `orders.routing-lists-template.item.get` template permission
=> UIREC-268: add missing template permission

CHANGELOG.md, package.json, src/Receiving.js, src/TitleDetails/AddPieceModal/AddPieceModal.js, src/TitleDetails/AddPieceModal/AddPieceModal.test.js, src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js, src/TitleDetails/AddPieceModal/PieceFields/PieceFields.js, src/TitleDetails/TitleDetails.js, src/TitleDetails/TitleDetails.test.js, src/TitleDetails/TitleDetailsContainer.js, src/TitleDetails/TitleDetailsContainer.test.js, src/TitleDetails/constants.js, src/TitleReceive/TitleReceive.js, src/TitleReceive/TitleReceiveContainer.js, src/TitleReceive/TitleReceiveContainer.test.js, src/TitleReceive/TitleReceiveList.js, src/common/components/LineLocationsView/LineLocationsView.js, src/common/components/LineLocationsView/LineLocationsView.test.js, src/common/hooks/useReceive.js
https://folio-org.atlassian.net/browse/UIREC-365
In ECS mode with the "Central ordering" setting activated, the user should be able to select an affiliation where the location/holding of the piece will be chosen.
Use ACQ components designed to determine the state of the "Central Ordering" setting and load locations/holdings depending on the settings.
https://github.com/folio-org/ui-receiving/assets/88109087/a27b6ebd-b520-441c-9808-33a217d9a642
- Do JIRAs exist to update the …
=> UIREC-365   Add Affiliation dropdown to Piece form and fullscreen receiving view

CHANGELOG.md, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceForm.test.js
[UIREC-377](https://folio-org.atlassian.net/browse/UIREC-377): Clear Item details when "Save and create another" option for adding electronic piece
https://github.com/user-attachments/assets/0c172edb-63d3-4ab0-98c0-4a618ba5cd7a …
=> UIREC-377: Clear Item details when "Save and create another" option for adding electronic piece

CHANGELOG.md, src/Piece/PieceForm/PieceFields/PieceFields.js, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceForm.test.js
[UIREC-361](https://folio-org.atlassian.net/browse/UIREC-361): ECS - "Select holdings" and "Affiliation" fields on "Edit piece" form for Unreceivable piece should be NOT editable
https://github.com/user-attachments/assets/14df5f6e-b071-4ace-accd-a78a22916e78
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UIREC-361: ECS - "Select holdings" and "Affiliation" fields on "Edit piece" form for Unreceivable piece should be NOT editable

package.json, src/TitleDetails/BoundItemsList/hooks/useBoundItems/useBoundItems.js, src/TitleDetails/TitleDetails.js
`<IfInterface>` check interface version in the major version borders, so `version="13.2"` is equivalent to `^13.2`, not `>=13.2`. As an alternative we could use `version="13.2 14"`, but we have to remember about updating the version in this place. So it makes sense to specify minimal available version for `inventory` interface (in borders of 13) 
https://github.com/folio-org/stripes-core/blob/0e4d2b45f69612c1ffffd7bf47c06c3c14a8ded4/src/discoverServices.js#L325-L339
=> Update min inventory interface version

CHANGELOG.md, package.json, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceForm.test.js, src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.js, src/Piece/PieceForm/PieceFormContainer.test.js, src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js, src/TitleReceive/TitleReceiveContainer.js, src/TitleReceive/TitleReceiveContainer.test.js, src/common/components/LineLocationsView/LineLocationsView.js, src/common/hooks/index.js, src/common/hooks/useReceivingTenantIdsAndLocations.js
[UIREC-411](https://folio-org.atlassian.net/browse/UIREC-411): ECS - fix user with no affiliation to the location in POL can not add pieces to the receiving title related to that POL
https://github.com/user-attachments/assets/4eb79045-7e03-4bb1-b73d-5474ac76dced
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UIREC-411: ECS - fix user with no affiliation to the location in POL can not add pieces to the receiving title related to that POL

src/Piece/PieceForm/PieceFields/PieceFields.js, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceFormContainer.js, src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js, src/TitleReceive/TitleReceiveContainer.js, src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.js, src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.test.js
Revert: [UIREC-393](https://folio-org.atlassian.net/browse/UIREC-393) invalid reference issues due to BE resolving the invalid holding/locations data
https://github.com/user-attachments/assets/77215d6b-6f3c-4df0-b59b-13d49599a8bb …
=> revert: UIREC-393 invalid reference issues due to BE resolving the invalid holding/locations data

CHANGELOG.md, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.js, src/Piece/PieceForm/PieceFormActionButtons/constants.js, src/Piece/PieceForm/PieceFormActionButtons/utils.test.js, src/Piece/constants.js, translations/ui-receiving/en.json
https://folio-org.atlassian.net/browse/UIREC-413
https://github.com/user-attachments/assets/88c93a5c-0e48-4688-b80d-f8b4475cfcee …
=> UIREC-413 Add 'Mark late' action to the piece form action menu

CHANGELOG.md, src/Piece/constants.js, src/TitleDetails/TitleDetails.js, src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js, src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.test.js
https://folio-org.atlassian.net/browse/UIREC-362
Declaratively hide and disable expected pieces' actions.
https://github.com/user-attachments/assets/b1bf090b-1b94-4144-8e5e-031569a4ddc7
- Hide vs Disable - https://ux.folio.org/docs/guidelines/ux-patterns/hiding-vs-disabling-elements-ux-pattern/
Ideally all of the PRs involved in breaking changes would be …
=> UIREC-362 Hide 'Add piece' action when related order has 'Pending' status and 'Synchronized' workflow

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIREC-430
Add `orders.wrapper-pieces.*.get` permissions to make it possible to view claims. …
=> UIREC-430 Add permissions to view claims

CHANGELOG.md, src/Piece/PieceForm/PieceForm.js, src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.js
=> UIREC-428 Fix disable state on Piece form
