- translations/ui-receiving/it_IT.json
> Update translation strings as of 20190313T213403

- translations/ui-receiving/es_ES.json
> Update translation strings as of 20190425T181703

- translations/ui-receiving/ar.json
> Update translation strings as of 20190517T183537

- translations/ui-receiving/it_IT.json
- translations/ui-receiving/zh_CN.json
> Update translation strings as of 20190729T163855

- translations/ui-receiving/ar.json
> Update translation strings as of 20190807T131714

- translations/ui-receiving/it_IT.json
> Update translation strings as of 20190919T124724

- translations/ui-receiving/it_IT.json
- translations/ui-receiving/zh_CN.json
> Update translation strings as of 20190925T125755

- translations/ui-receiving/ru.json
> Update translation strings as of 20191104T173556

- translations/ui-receiving/it_IT.json
> Update translation strings as of 20191115T154823

- translations/ui-receiving/fr_FR.json
> Update translation strings as of 20191119T231120

- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
> Update translation strings as of 20191220T210632

- package.json
To add a proper perms for new module …
> add perms for new module

- CHANGELOG.md
- package.json
- src/Receiving.js
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/renderNewButton.js
- src/TitleForm/ProductIdDetailsForm.js
- src/TitleForm/TitleForm.js
- src/TitleForm/TitleFormContainer.js
- src/TitleForm/constants.js
- src/TitleForm/index.js
- src/common/resources/titleResources.js
- translations/ui-receiving/en.json
Form for add Title
https://issues.folio.org/browse/UIREC-28
While it's helpful for reviewers …
> UIREC-28 Add Title for receiving/check-in

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200109T152437

- CHANGELOG.md
- src/Receiving.js
- src/ReceivingList/ReceivingList.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleDetails/TitleInformation/TitleInformation.js
- src/TitleDetails/TitleInformation/index.js
- src/TitleDetails/constants.js
- src/TitleDetails/index.js
- src/common/constants/api.js
- src/common/resources/titleResources.js
- translations/ui-receiving/en.json
View title in receiving area
https://issues.folio.org/browse/UIREC-27
While it's helpful for …
> UIREC-27 View title in receiving area

- package.json
- src/ReceivingList/ReceivingList.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleEdit/TitleEdit.js
- src/TitleEdit/TitleEditContainer.js
- src/TitleEdit/index.js
- translations/ui-receiving/en.json
Edit Title for receiving/check-in, initial implementation due to reduced API support.
https://issues.folio.org/browse/UIREC-37 …
> UIREC-37 Edit Title for receiving/check-in

- CHANGELOG.md
- src/TitleForm/TitleFormContainer.js
Merge after https://github.com/folio-org/ui-receiving/pull/58
Add success message for create title
https://issues.folio.org/browse/UIREC-34
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIREC-34 Add success message for create title

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListSearchConfig.js
- translations/ui-receiving/en.json
Receiving: search for titles
https://issues.folio.org/browse/UIREC-31
While it's helpful for …
> UIREC-31 Receiving: search for titles

- src/ReceivingList/ReceivingListSearchConfig.js
remove the barcode as a search option due to no easy way to implement this on the back-end and low customer's priority.
https://issues.folio.org/browse/UIREC-31
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIREC-31 remove barcode

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200117T173544

- CHANGELOG.md
- Jenkinsfile
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingList.test.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/utils.js
- src/ReceivingList/utils.test.js
- src/common/constants/api.js
- src/common/resources/index.js
- src/common/resources/locationResources.js
- src/common/resources/orderLineResources.js
- translations/ui-receiving/en.json
Receiving: search for titles - Column headers …
> UIREC-39 Receiving: search for titles - Column headers

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingList.test.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/constants.js
- src/ReceivingList/utils.js
- src/ReceivingList/utils.test.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-29 …
> UIREC-29 Receiving: filter titles

- Jenkinsfile
- package.json
- src/ReceivingList/ReceivingList.js
- test/bigtest/.eslintrc
- test/bigtest/helpers/setup-application.js
- test/bigtest/index.js
- test/bigtest/interactors/TitlesListInteractor.js
- test/bigtest/interactors/application.js
- test/bigtest/interactors/index.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/configs/index.js
- test/bigtest/network/configs/titles.js
- test/bigtest/network/factories/title.js
- test/bigtest/network/index.js
- test/bigtest/network/models/title.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/title.js
- test/bigtest/tests/application-test.js
- test/bigtest/tests/title-list-test.js
> add bigtest

- src/ReceivingList/ReceivingList.js
- src/ReceivingList/utils.js
https://issues.folio.org/browse/UIREC-39 …
> UIREC-39 fix expected data value

- src/TitleDetails/PiecesActions/ExpectedPiecesActions.js
- src/TitleDetails/PiecesActions/ReceivedPiecesActions.js
- translations/ui-receiving/en.json
Remove unused piece action
(per Dennis comment to [ UIREC-35](https://issues.folio.org/browse/UIREC-35?focusedCommentId=69533&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-69533)) …
> Remove unused piece action

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/utils.js
Add piece button showing for Titles that are not "Manually add pieces for receiving"
https://issues.folio.org/browse/UIREC-43 …
> UIREC-43 Add piece button showing for Titles that are not "Manually add pieces for receiving"

- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js
- src/TitleDetails/PiecesActions/ExpectedPiecesActions.js
- src/TitleDetails/PiecesActions/ReceivedPiecesActions.js
- src/TitleDetails/PiecesList/PiecesList.test.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/TitleInformation/TitleInformation.js
- src/TitleDetails/TitleInformation/TitleInformation.test.js
have more tests
While it's helpful for reviewers to help identify potential problems, …
> TitleDetails unit tests

- src/ReceivingList/ReceivingList.js
- src/ReceivingList/renderNewButton.js
- src/TitleForm/TitleForm.js
- src/TitleForm/TitleFormContainer.js
* save search params when going to and returning from Create/Edit
screen;
* fix selecting instance from plugin with `null` pub date;
* After create Title got to the Details pane of ths Title.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> some improvements before the demo

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js
- src/TitleDetails/PiecesList/PiecesList.css
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/PiecesList/PiecesList.test.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/constants.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-52 …
> UIREC-52 Update title record Expected and Received accordion columns

- package.json
> bump-up stripes v3

- src/TitleReceive/OpenedRequestsModal/OpenedRequestsModal.css
- src/TitleReceive/OpenedRequestsModal/OpenedRequestsModal.js
- src/TitleReceive/OpenedRequestsModal/index.js
- src/TitleReceive/TitleReceiveContainer.js
- test/bigtest/interactors/TitleReceiveInteractor.js
- test/bigtest/network/factories/request.js
- test/bigtest/tests/piece/receive-piece-test.js
- translations/ui-receiving/en.json
While moving Receiving functionality from ui-orders, some part was missing
While it's …
> add Open Requests modal (ported from ui-orders)

- translations/ui-receiving/en.json
> new messages from story review

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200309T000645

- src/TitleDetails/AddPieceModal/AddPieceModal.js
> disable location select and remove margin for Add item

- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
https://issues.folio.org/browse/UIREC-60 …
> UIREC-60 Improve Location filter on the Titles list to use location look-up

- CHANGELOG.md
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleInformation/TitleInformation.js
- src/TitleDetails/TitleInformation/TitleInformation.test.js
https://issues.folio.org/browse/UIREC-62 …
> UIREC-62 Hotlink POL number in receiving to POL

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleReceive/TitleReceive.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveList.js
https://issues.folio.org/browse/UIREC-59 …
> UIREC-59 Use only select Location plugin

- CHANGELOG.md
- package.json
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/POLDetails/index.js
- src/TitleDetails/Title/Title.js
- src/TitleDetails/Title/Title.test.js
- src/TitleDetails/Title/index.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleDetails/TitleInformation/TitleInformation.js
- src/TitleDetails/TitleInformation/TitleInformation.test.js
- src/TitleDetails/constants.js
- src/common/constants/api.js
- test/bigtest/interactors/TitleDetailsInteractor.js
- test/bigtest/network/config.js
- test/bigtest/tests/title/title-details-test.js
- translations/ui-receiving/en.json
- Title information accordion is closed by default
- POL details' accordion
- Title appears above the title information accordion
- When the related purchase order has a workflow status of closed - an alert appears at top of title with message - "Purchase order is closed - [reason for closure]"
https://issues.folio.org/browse/UIREC-66
Ideally all of the …
>  UIREC-66 POL POL details displaying under Title information accordion

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/TitleDetailsContainer.js
- translations/ui-receiving/en.json
Edit piece modal: Incorrect button label
https://issues.folio.org/browse/UIREC-67
While it's …
> UIREC-67 Edit piece modal: Incorrect button label

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200325T162106

- translations/ui-receiving/ar.json
- translations/ui-receiving/pt_BR.json
> Update translation strings as of 20200331T152557

- CHANGELOG.md
- package.json
per comment in https://issues.folio.org/browse/UIOR-537
there are some permission missed for Location lookup
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> Uior 537 fix select location permissions

- translations/ui-receiving/pt_BR.json
> Update translation strings as of 20200403T124750

- package.json
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- test/bigtest/interactors/TitlesListInteractor.js
- test/bigtest/tests/title-list-test.js
* Some permissions were missed;
* use common component ResultStatusMessage;
While it's …
> add missing permission, use `ResultStatusMessage`

- package.json
> add missing tags permission

- CHANGELOG.md
- src/TitleReceive/TitleReceive.js
- src/TitleReceive/TitleReceive.test.js
- src/TitleReceive/TitleReceiveContainer.js
- test/bigtest/interactors/TitleReceiveInteractor.js
- test/bigtest/tests/piece/receive-piece-test.js
- test/bigtest/tests/title/title-details-test.js
https://issues.folio.org/browse/UIREC-70 …
> UIREC-70 Display receiving note in receiving view

- CHANGELOG.md
- src/TitleDetails/PiecesList/PiecesList.js
https://issues.folio.org/browse/UINV-138 …
> UINV-138 Align actions icons in table to right hand side of view pane

- src/TitleDetails/PiecesList/PiecesList.js
https://issues.folio.org/browse/UINV-138 …
> UINv-138 align last column only when there is an arrow at the end

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/TitleDetails.js
Fill PO Line id on create Item request from Add Item modal
https://issues.folio.org/browse/UIREC-78
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIREC-78 pass poLine id to Item create API

- src/common/utils/getHydratedPieces.js
Show status `in process` instead of `order closed` per new requirement in tickets comment
https://issues.folio.org/browse/UIREC-78 …
> UIREC-78 show status in process instead of order closed

- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200424T193712

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
Organizations is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151 …
> UIORGS-151 using the same Expand/Collapse

- package.json
> bump up okapi iface `pieces`

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/constants.js
- src/common/constants/piece.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-42 …
> UIREC-42 Filter Titles by piece status and AcqUnit

- CHANGELOG.md
- src/TitleForm/TitleForm.js
https://issues.folio.org/browse/UIREC-47 …
> UIREC-47 Add Title not using instance lookup

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-80 …
> UIREC-80 Update to Stripes v4

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200513T135229

- CHANGELOG.md
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
https://issues.folio.org/browse/UIREC-83
`titleId` becomes a required field for piece creation/editing
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIREC-83 Suppot back-end changes in related story

- translations/ui-receiving/ru.json
> Update translation strings as of 20200515T182823

- translations/ui-receiving/fr_FR.json
> Update translation strings as of 20200519T123842

- src/TitleForm/TitleForm.js
- translations/ui-receiving/en.json
> fix console warning

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200521T142352

- translations/ui-receiving/ru.json
> Update translation strings as of 20200522T132417

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/AddPieceModal/index.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/constants.js
fix Add Piece modal keeps values from previously edited piece
https://issues.folio.org/browse/UIREC-92
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIREC-92 fix stale form values

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200526T141248

- CHANGELOG.md
- package.json
> backport-release-of-v.1.0.4

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200528T173426

- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveList.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/utils/getDehydratedPiece.js
- src/common/utils/receive.js
https://issues.folio.org/browse/UIREC-91 …
> UIREC-91 pass right materialType and loanType

- src/common/components/CreateItemField/CreateItemField.js
https://issues.folio.org/browse/UIREC-91 …
> UIREC-91 go to item instead of instance

- src/TitleDetails/TitleDetailsContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/utils/getDehydratedPiece.js
- src/common/utils/getHydratedPieces.js
- src/common/utils/ifMissingPermanentLoanTypeId.js
- src/common/utils/index.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-91 …
> UIREC-91 fix direct link to item view, error handling

- src/TitleReceive/TitleReceiveList.js
> UIREC-91 disable varcode and callnumber

- src/ReceivingList/utils.js
Receiving search result list - sorting on columns
https://issues.folio.org/browse/UIREC-86 …
> UIREC-86 pass correct sort field name to back-end

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/TitleDetails.js
- src/common/components/CreateItemField/CreateItemField.js
- test/bigtest/tests/piece/edit-received-piece-test.js
Ability to edit unreceived pieces
https://issues.folio.org/browse/UIREC-94
While it's …
> UIREC-94 Ability to edit unreceived pieces

- src/TitleEdit/TitleEditContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
> UIOR-567 fix missing callouts

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
Action buttons are not aligning to the right and are displaying states incorrectly
https://issues.folio.org/browse/UIREC-46 …
> UIREC-46 disable submit

- translations/ui-receiving/fr_FR.json
> Update translation strings as of 20200604T202430

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200615T161518

- translations/ui-receiving/ru.json
> Update translation strings as of 20200624T130324

- CHANGELOG.md
- package.json
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleDetails/TitleDetailsContainer.test.js
- test/bigtest/network/config.js
- test/bigtest/tests/piece/add-piece-test.js
- test/bigtest/tests/piece/edit-piece-test.js
- test/bigtest/tests/piece/edit-received-piece-test.js
- test/bigtest/tests/piece/receive-piece-test.js
- test/bigtest/tests/piece/unreceive-piece-test.js
- test/bigtest/tests/piece/unreceive-pieces-test.js
- test/bigtest/tests/title-list-test.js
- test/bigtest/tests/title/title-details-test.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-95 …
> UIREC-95 Display 'Vendor', 'Material supplier', 'Access provider' and 'Order type' in title view pane

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200709T123052

- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/ru.json
> Update translation strings as of 20200710T132222

- translations/ui-receiving/fr_FR.json
> Update translation strings as of 20200716T140311

- CHANGELOG.md
- src/TitleReceive/TitleReceiveList.js
- src/TitleUnreceive/TitleUnreceiveList.js
- src/common/components/CreateItemField/CreateItemField.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-73
aria labels for unlabeled controls
While it's …
> UIREC-73 Accessibility Error: Form elements must have labels

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/TitleDetails/AddPieceModal/AddPieceModal.js
Update subheading of the Receiving landing page Search results pane
https://issues.folio.org/browse/UIREC-96
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UIREC-96 Update subheader of Receiving list pane

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20200727T130814

- translations/ui-receiving/it_IT.json
> Update translation strings as of 20200820T141724

- translations/ui-receiving/zh_CN.json
> Update translation strings as of 20200827T215834

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingList.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/TitleInformation/TitleInformation.js
- src/TitleForm/TitleForm.js
- src/TitleReceive/TitleReceiveList.js
- src/TitleUnreceive/TitleUnreceiveList.js
- src/common/components/CreateItemField/CreateItemField.js
https://issues.folio.org/browse/UIREC-98 …
> UIREC-98 Update view pane to display null as hyphen - Receving

- CHANGELOG.md
- package.json
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
https://issues.folio.org/browse/UIREC-97 …
> Release v1.2.0

- CHANGELOG.md
- src/TitleDetails/TitleDetails.js
- test/bigtest/tests/title/title-details-test.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-100 …
> UIREC-100 Display warning modal when user trying to receive against a closed Order

- translations/ui-receiving/ar.json
- translations/ui-receiving/ca.json
- translations/ui-receiving/da.json
- translations/ui-receiving/de.json
- translations/ui-receiving/en_GB.json
- translations/ui-receiving/en_SE.json
- translations/ui-receiving/en_US.json
- translations/ui-receiving/es.json
- translations/ui-receiving/es_419.json
- translations/ui-receiving/es_ES.json
- translations/ui-receiving/fr.json
- translations/ui-receiving/fr_FR.json
- translations/ui-receiving/he.json
- translations/ui-receiving/hi_IN.json
- translations/ui-receiving/hu.json
- translations/ui-receiving/it_IT.json
- translations/ui-receiving/ja.json
- translations/ui-receiving/ko.json
- translations/ui-receiving/pl.json
- translations/ui-receiving/pt_BR.json
- translations/ui-receiving/pt_PT.json
- translations/ui-receiving/ru.json
- translations/ui-receiving/ur.json
- translations/ui-receiving/zh_CN.json
- translations/ui-receiving/zh_TW.json
> Update translation strings as of 20201026T135354

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/utils.js
- src/common/resources/orderLineResources.js
- translations/ui-receiving/en.json
Orders and receiving - want to see that an order is closed in search result list
https://issues.folio.org/browse/UIOR-620 …
> UIOR-620 show order status in titles list

- src/TitleDetails/TitleDetails.js
- test/bigtest/tests/piece/add-piece-test.js
Display warning modal when user trying quick receive against a closed Order
https://issues.folio.org/browse/UIREC-100?focusedCommentId=90160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-90160 …
> UIREC-100 Display warning modal when user trying quick receive against a closed Order

- CHANGELOG.md
- src/common/components/CreateItemField/CreateItemField.js
- src/common/components/CreateItemField/CreateItemField.test.js
- src/common/utils/getHydratedPieces.js
Piece displays as connected to an item when connected item record has been deleted.
https://issues.folio.org/browse/UIREC-102 …
> UIREC-102 check if item exists

- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIOR-620 …
> UIOR-620 new label

- translations/ui-receiving/ar.json
- translations/ui-receiving/fr_FR.json
> Update translation strings as of 20201124T212804

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIREC-110 …
> UIREC-110 Add personal data disclosure form

- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
https://issues.folio.org/browse/UIREC-113 …
> UIREC-113 limit delete btn only for manually piece

- package.json
https://issues.folio.org/browse/UIREC-115 …
> UIREC-115 Update stripes-cli to v2

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
https://issues.folio.org/browse/UIREC-118 …
> UIREC-118 Calendar widget cutoff by modal

- CHANGELOG.md
- src/ReceivingList/ReceivingListSearchConfig.js
- src/ReceivingList/utils.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-119 …
> UIREC-119 Add option to search by Vendor reference number

- CHANGELOG.md
- package.json
> Release v1.3.2

- package.json
https://issues.folio.org/browse/UIREC-126 …
> UIREC-126 bump circulation interface to 10.0

- package.json
https://issues.folio.org/browse/UIREC-126 …
> UIREC-126 wider diapason of interface versions

- src/ReceivingList/ReceivingList.js
- src/TitleDetails/TitleDetailsContainer.js
https://issues.folio.org/browse/UIREC-127 …
> UIREC-127 Resizable Panes - Persistence

- package.json
https://issues.folio.org/browse/UIREC-130 …
> UIREC-130 Permissions for select instance plugin

- package.json
https://issues.folio.org/browse/UIREC-129 …
> UIREC-129 Add missed permissions

- CHANGELOG.md
- package.json
- test/bigtest/interactors/index.js
- test/bigtest/tests/piece/add-piece-test.js
https://issues.folio.org/browse/UIREC-131 …
> UIREC-131 v1.3.3 release

- package.json
- src/Receiving.js
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingList.test.js
- src/TitleDetails/TitleDetails.js
- src/TitleEdit/TitleEditContainer.js
- src/TitleForm/TitleForm.js
- src/TitleForm/TitleFormContainer.js
- src/TitleReceive/TitleReceive.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleUnreceive/TitleUnreceive.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
- test/bigtest/tests/piece/edit-piece-test.js
- test/bigtest/tests/piece/edit-received-piece-test.js
- test/bigtest/tests/piece/receive-piece-test.js
- test/bigtest/tests/piece/unreceive-piece-test.js
- test/bigtest/tests/title/title-details-test.js
https://issues.folio.org/browse/UIREC-117 …
> UIREC-117 Apply baseline keyboard shortcuts

- CHANGELOG.md
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/constants.js
- src/ReceivingList/utils.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-120
add date range filter components from stripes-acq
more coverage will be added as part of migration to jest, for now utils are covered
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIREC-120 Receiving: Add filters for Expected receipt date and Received date

- CHANGELOG.md
- src/Receiving.js
- src/ReceivingList/ReceivingList.js
- src/TitleDetails/TitleDetails.js
- src/TitleForm/TitleForm.js
- src/TitleReceive/TitleReceive.js
- src/TitleUnreceive/TitleUnreceive.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/tests/title/title-details-test.js
https://issues.folio.org/browse/UIREC-134 …
> UIREC-134 Implement keyboard shortcut modal

- CHANGELOG.md
- Jenkinsfile
- package.json
https://issues.folio.org/browse/UIREC-125 …
> UIREC-125 Compile Translation Files into AST

- CHANGELOG.md
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/TitleDetails.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-114 …
> UIREC-114 Display requester from POL

- CHANGELOG.md
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/TitleDetails.js
https://issues.folio.org/browse/UIREC-137 …
> UIREC-137 Fix Expected receipt date

- CHANGELOG.md
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
https://issues.folio.org/browse/UIREC-143 …
> UIREC-143 CANNOT receive pieces against package POL

- CHANGELOG.md
- src/ReceivingList/ReceivingListContainer.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-142 …
> UIREC-142 Receiving search: 'No records found' when location is removed

- CHANGELOG.md
- package.json
> Release v1.3.4

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
https://issues.folio.org/browse/UIREC-146 …
> UIREC-146 The Delete button is displayed in the Add piece pop up (new piece)

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-141 …
> UIREC-141 permission sets should avoid .all permissions

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/PiecesList/PiecesList.test.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/constants.js
https://issues.folio.org/browse/UIREC-147 …
> UIREC-147 Ability to sort expected/received pieces

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-145 …
> Release v.1.4.1

- CHANGELOG.md
- src/ReceivingList/utils.js
https://issues.folio.org/browse/UIREC-149 …
> UIREC-149 Location filter not returning results

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-150 …
> Release v1.4.2

- package.json
- src/ReceivingList/ReceivingListContainer.test.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
- src/ReceivingList/ReceivingListSearchConfig.test.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
- src/TitleDetails/TitleDetails.test.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.test.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.test.js
- src/TitleDetails/TitleDetailsContainer.test.js
- src/TitleEdit/TitleEditContainer.test.js
- src/TitleForm/ContributorsForm.js
- src/TitleForm/ContributorsForm.test.js
- src/TitleForm/ProductIdDetailsForm.test.js
- src/TitleForm/TitleForm.test.js
- src/TitleForm/TitleFormContainer.test.js
- src/TitleReceive/OpenedRequestsModal/OpenRequestModal.test.js
- src/TitleReceive/TitleReceive.test.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveContainer.test.js
- src/TitleUnreceive/TitleUnreceive.test.js
- src/TitleUnreceive/TitleUnreceiveContainer.test.js
> FAT-41 UI tests replacement with RTL/Jest

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-55 …
> UIREC-55 Use mod-orders for piece queries

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsContainer.js
- src/common/constants/errorCodes.js
- src/common/constants/index.js
- src/common/utils/handleCommonErrors.js
- src/common/utils/handleCommonErrors.test.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-132 …
> UIREC-132 Allow user to adjust order quantity and location/hodlings connection from receiving ui

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-154 …
> UIREC-154 increment stripes to v7

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
- src/TitleReceive/TitleReceive.js
- src/TitleReceive/TitleReceive.test.js
- src/TitleReceive/TitleReceiveContainer.js
- src/common/components/LineLocationsView/LineLocationsView.js
- src/common/components/LineLocationsView/LineLocationsView.test.js
- src/common/components/LineLocationsView/index.js
- src/common/components/index.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-163 …
> UIREC-163 Display line locations on piece form

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.test.js
- src/TitleReceive/TitleReceiveList.js
- src/common/utils/receive.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-160 …
> UIREC-160 Display Copy number, Enumeration AND Chronology in Piece form

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/constants.js
https://issues.folio.org/browse/UIREC-158 …
> UIREC-158 Update Received/Expected piece table columns

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingList.test.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListContainer.test.js
- src/ReceivingList/hooks/index.js
- src/ReceivingList/hooks/useReceiving/index.js
- src/ReceivingList/hooks/useReceiving/useReceiving.js
- src/ReceivingList/hooks/useReceiving/useReceiving.test.js
https://issues.folio.org/browse/UIREC-164 …
> UIREC-164 Receiving - Implement MCL Next/Previous pagination

- src/ReceivingList/ReceivingListContainer.js
https://issues.folio.org/browse/UIREC-164 …
> UIREC-164 Set the limit of receiving items to 50 per request

- CHANGELOG.md
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/utils.js
- src/ReceivingList/utils.test.js
https://issues.folio.org/browse/UIREC-172 …
> UIREC-172 Display Holding OR Location name in location column in search

- CHANGELOG.md
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-173 …
> UIREC-173 Filter label contains extra 's'

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.test.js
https://issues.folio.org/browse/UIREC-174 …
> UIREC-174 Disable add and remove piece when order is pending

- CHANGELOG.md
- src/TitleReceive/TitleReceiveList.js
- src/TitleUnreceive/TitleUnreceive.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveList.js
- src/common/components/LineLocationsView/LineLocationsView.js
https://issues.folio.org/browse/UIREC-182 …
> UIREC-182 Display "Invalid reference" when Holdings ID is not valid

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingList.test.js
https://issues.folio.org/browse/UIREC-185 …
> Release v2.0.1

- CHANGELOG.md
- src/TitleEdit/TitleEditContainer.js
https://issues.folio.org/browse/UIREC-189 …
> UIREC-189 Allow user to select instance for Title AND edit title from POL view

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/PiecesList/PiecesList.css
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/constants.js
https://issues.folio.org/browse/UIREC-193 …
> UIREC-193 Display comment in receiving in column rather than on hover

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/PiecesList/PiecesList.test.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.test.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.test.js
- src/TitleDetails/constants.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-196 …
> UIREC-196 Allow user to choose columns

- CHANGELOG.md
- src/TitleDetails/TitleDetailsContainer.js
https://issues.folio.org/browse/UIREC-197 …
> UIREC-197 Receiving app is reaching the display limit of 1000 pieces

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-200 …
> UIREC-200 v2.0.3 bugfix release

- package.json
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleReceive/TitleReceiveList.js
- src/TitleUnreceive/TitleUnreceiveList.js
> bump up es-lint version

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
https://issues.folio.org/browse/UIREC-208 …
> UIREC-208 Hide "Suppress from discovery" toggle from Piece form

- CHANGELOG.md
- src/TitleDetails/PiecesList/PiecesList.js
https://issues.folio.org/browse/UIREC-211 …
> UIREC-211 Piece received date is not timezone formatted

- CHANGELOG.md
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.test.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.test.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetails.test.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
- src/TitleDetails/TitleDetailsContainer.js
- src/TitleDetails/constants.js
- src/common/hooks/index.js
- src/common/hooks/usePaginatedPieces/index.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.test.js
- src/common/utils/getHydratedPieces.js
https://issues.folio.org/browse/UIREC-213 …
> UIREC-213 Pagination - Prevent receiving app from reaching the 1000 piece display limit

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-177 …
> UIREC-177 refactor psets away from backend '.all' permissions

- CHANGELOG.md
- src/TitleReceive/TitleReceiveList.js
- src/common/utils/getHydratedPieces.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-218
https://issues.folio.org/browse/UIREC-214
While …
> UIREC-214 UIREC-218 Item status unclear in receiving screen

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/DeleteHoldingsModal/DeleteHoldingsModal.js
- src/TitleDetails/DeletePieceModal/DeletePieceModal.js
- src/TitleDetails/ExpectedPiecesList/ExpectedPiecesList.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/ReceivedPiecesList/ReceivedPiecesList.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.test.js
- src/TitleForm/ContributorsForm.js
- src/TitleForm/ProductIdDetailsForm.js
- src/TitleReceive/OpenedRequestsModal/OpenedRequestsModal.js
https://issues.folio.org/browse/UIREC-221 …
> UIREC-221 ui-receiving accessibility analysis

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-224 …
> UIREC-224 Replace deprecated permission search.instances.facets.collection.get

- CHANGELOG.md
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
- src/ReceivingList/constants.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-205 …
> UIREC-205 Filter Receiving titles by 'Rush'

- CHANGELOG.md
- src/TitleUnreceive/TitleUnreceiveList.js
https://issues.folio.org/browse/UIREC-226 …
> UIREC-226 Add Caption detail to the Unreceive screen

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
https://issues.folio.org/browse/UIREC-227 …
> UIREC-227 Select filter should announce the number of Results in the Results List pane header

- .eslintrc
- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-232 …
> UIREC-232 replace babel-eslint with @babel/eslint-parser

- CHANGELOG.md
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-75 …
> UIREC-75 Add translations for permissions

- CHANGELOG.md
- package.json
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
https://issues.folio.org/browse/UIREC-237 …
> UIREC-237 ui-receiving: module warnings analysis

- src/TitleEdit/TitleEditContainer.test.js
- src/TitleForm/TitleFormContainer.test.js
https://github.com/folio-org/ui-receiving/pull/388#issuecomment-1181698938
While it's …
>  Fix unit tests to run GA actions on Node v16

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
https://issues.folio.org/browse/UIREC-244 …
> UIREC-244 Results List | Hyperlink one column to improve accessibility

- CHANGELOG.md
- src/TitleReceive/TitleReceiveContainer.js
- src/common/hooks/useQuickReceive.js
- src/common/hooks/useQuickReceive.test.js
- src/common/utils/getItemById.js
- src/common/utils/getItemById.test.js
- src/common/utils/getReceivingPieceItemStatus.js
- src/common/utils/getReceivingPieceItemStatus.test.js
- src/common/utils/index.js
https://issues.folio.org/browse/UIREC-249 …
> UIREC-249 Item statuses other than `Order closed` or `On order` are set to `In process` upon receiving

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-252 …
> UIREC-252 loose plugin dependencies permit incompatible versions

- CHANGELOG.md
- package.json
- src/Receiving.js
- src/ReceivingList/ReceivingList.js
https://issues.folio.org/browse/UIREC-253
Provide `resetFilters` state on location change to use hook for reset active filters …
> UIREC-253 No results found shown after return to search page

- CHANGELOG.md
- src/TitleEdit/TitleEditContainer.js
- src/TitleForm/TitleFormContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
https://issues.folio.org/browse/UIREC-251 …
> UIREC-251 Avoid using `setTimeout()` in handlers

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-256 …
> UIREC-256 Support `inventory` interface version `13.0`

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-256
update missed `search` interface
While it's …
> UIREC-256 Align the module with API breaking change

- package.json
https://issues.folio.org/browse/UIREC-261
init PR - #424 
update permission sets with `orders.pieces.item.get` permission …
> UIREC-261 add missed perm to get a piece

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIREC-259
Replica of #429 
While it's helpful for reviewers …
> UIREC-259 unpin @rehooks/local-storage

- CHANGELOG.md
- src/TitleReceive/OpenedRequestsModal/OpenedRequestsModal.js
> UIREC-278 Receiving an item with an open request, the warning dialogue shows 'undefined' instead of title.

- CHANGELOG.md
- src/ReceivingList/ExportSettingsModal/constants.js
- src/ReceivingList/ExportSettingsModal/utils/createExportReport.js
- src/TitleDetails/PiecesList/PiecesList.js
- src/TitleDetails/constants.js
- translations/ui-receiving/en.json
https://issues.folio.org/browse/UIREC-306
Include `receivingStatus`, `internalNote`, and `externalNote` fields in the CSV export report.
https://github.com/folio-org/ui-receiving/assets/88109087/0720f761-8d87-492e-b16f-d44ed661a651 …
> UIREC-306 Add CSV export options for new piece statuses

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/ItemFields/ItemFields.js
- src/TitleDetails/AddPieceModal/ItemFields/index.js
- src/TitleDetails/AddPieceModal/PieceFields/PieceFields.js
- src/TitleDetails/AddPieceModal/PieceFields/index.js
- src/TitleDetails/constants.js
- src/TitleReceive/TitleReceiveList.js
- src/common/hooks/useReceive.js
- src/common/utils/getDehydratedPiece.js
https://issues.folio.org/browse/UIREC-296
Add missing fields into modal and full screen view:
Split piece's and item's related fields into separate components for better code maintenance. Display 4 fields in a row instead of 2 in the large screens.
https://github.com/folio-org/ui-receiving/assets/88109087/36578044-05b3-4f3c-94e1-c3a7b102753e
Ideally all of …
> UIREC-296 Align the display of fields in full screen receiving view and piece edit form

- CHANGELOG.md
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/TitleDetails/TitleDetailsContainer.js
- src/common/utils/handleCommonErrors.js
https://issues.folio.org/browse/UIREC-309
---
> UIREC-309 Fix linter warnings across the module

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModalContainer.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsExpectedActions.test.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsUnreceivableActions.js
- src/TitleForm/TitleForm.js
- src/TitleForm/TitleForm.test.js
[UIREC-332](https://folio-org.atlassian.net/browse/UIREC-332) - UIREC-332: disable title action buttons if user not part of acquisition unit
https://github.com/folio-org/ui-receiving/assets/116072773/fb03a593-9384-4e72-b65c-89963a44c55e …
> UIREC-332: disable title action buttons if user not part of acquisition unit

- CHANGELOG.md
- src/ReceivingList/ReceivingList.js
- translations/ui-receiving/en.json
https://folio-org.atlassian.net/browse/UIREC-320
https://github.com/folio-org/ui-receiving/assets/88109087/90993d17-7018-484f-81f1-f65bdff3b7ed
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIREC-320 UX Consistency > Search results > Update HTML page title with search term entered

- CHANGELOG.md
- src/TitleDetails/TitleDetails.js
https://folio-org.atlassian.net/browse/UIREC-319
Update the HTML document title with the Title name when the third pane opens.
https://github.com/folio-org/ui-receiving/assets/116072773/bd079651-a84f-4875-ac04-0d3835a8c674 …
> UIREC-319: UX Consistency: Update HTML Page Title display when third pane (detail record) displays

- CHANGELOG.md
- src/TitleDetails/TitleDetails.css
- src/TitleDetails/TitleDetails.js
https://folio-org.atlassian.net/browse/UIREC-338 
Add more space for Receiving App title …
> UIREC-338: fix title spacing issue

- CHANGELOG.md
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
- src/TitleDetails/AddPieceModal/PieceFields/PieceFields.js
- translations/ui-receiving/en.json
https://folio-org.atlassian.net/browse/UIREC-333 - Add "Display to public" toggle on piece form
https://github.com/folio-org/ui-receiving/assets/116072773/c26b98f3-9066-4fe8-bb7d-8f6dd8f4aadd
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> UIREC-333: Add "Display to public" toggle on piece form

- package.json
- src/ReceivingList/ExportSettingsModal/constants.js
- src/ReceivingList/ExportSettingsModal/utils/createExportReport.js
- src/ReceivingList/ExportSettingsModal/utils/createExportReport.test.js
- src/ReceivingList/ExportSettingsModal/utils/fetchExportResources.js
- src/ReceivingList/ExportSettingsModal/utils/getExportData.js
- src/ReceivingList/ExportSettingsModal/utils/getExportData.test.js
- src/ReceivingList/hooks/useReceiving/useReceiving.js
- src/ReceivingList/hooks/useReceiving/useReceiving.test.js
- src/ReceivingList/utils.js
> UIREC-341 include username instead of uuid in csv export

- src/ReceivingList/ExportSettingsModal/constants.js
- src/ReceivingList/ExportSettingsModal/utils/createExportReport.js
> UIREC-341 use datetime instead of date for csv metadata

- CHANGELOG.md
- package.json
> Release v5.0.3

- CHANGELOG.md
- package.json
> Release v5.0.4

- CHANGELOG.md
- package.json
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetails.test.js
https://folio-org.atlassian.net/browse/UIREC-328 - Add RoutingList component
https://github.com/folio-org/ui-receiving/assets/116072773/b99277de-eba0-430c-959a-6c23e2d2f8ce
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIREC-328: Add RoutingList component

- src/ReceivingList/ReceivingList.js
- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/ReceivingListContainer.test.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
https://folio-org.atlassian.net/browse/UIREC-358
Initial PR: #521 
https://github.com/folio-org/ui-receiving/assets/88109087/6ba43a90-0a3f-46d0-bf03-dca804603636
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIREC-358 Display affiliations selection in the locations filter in the central tenant and with enabled setting

- CHANGELOG.md
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
- src/ReceivingList/constants.js
- translations/ui-receiving/en.json
[UIREC-323](https://folio-org.atlassian.net/browse/UIREC-323): Add bindery active facet to receiving
https://github.com/folio-org/ui-receiving/assets/116072773/a9f584a8-b90b-4465-ab25-29a90484e57c
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIREC-323: Add bindery active facet to receiving

- src/TitleDetails/AddPieceModal/PieceFields/PieceFields.js
- src/common/components/LineLocationsView/LineLocationsView.js
Fix small issue with the chronology field name, introduced in the https://github.com/folio-org/ui-receiving/pull/527
> UIREC-263 Pass proper name for the chronology field

- CHANGELOG.md
- package.json
- src/Receiving.js
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
- src/TitleDetails/POLDetails/POLDetails.js
- src/TitleDetails/POLDetails/POLDetails.test.js
- src/TitleDetails/RoutingList/RoutingList.js
- src/TitleDetails/RoutingList/RoutingList.test.js
- src/TitleDetails/RoutingList/constants.js
- src/TitleDetails/RoutingList/index.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetails.test.js
- src/TitleDetails/constants.js
- src/TitleDetails/index.js
- src/constants.js
[UIREC-268](https://folio-org.atlassian.net/browse/UIREC-268): print routing list from receiving app
https://github.com/folio-org/ui-receiving/assets/116072773/4de81092-465c-40ac-ab54-ac41dfae9fac
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIREC-268: print routing list from receiving app

- CHANGELOG.md
- package.json
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
- src/TitleDetails/AddPieceModal/PieceFields/PieceFields.js
- src/TitleDetails/BoundPiecesList/BoundPiecesList.js
- src/TitleDetails/BoundPiecesList/BoundPiecesList.test.js
- src/TitleDetails/BoundPiecesList/constants.js
- src/TitleDetails/BoundPiecesList/index.js
- src/TitleDetails/BoundPiecesList/utils.js
- src/TitleDetails/TitleDetails.js
- src/TitleDetails/TitleDetailsActions/TitleDetailsReceivedActions.js
- src/TitleDetails/constants.js
- src/TitleDetails/hooks/usePiecesList/usePiecesList.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- translations/ui-receiving/en.json
[UIREC-322:](https://folio-org.atlassian.net/browse/UIREC-322) Add Bound items accordion in receiving
https://github.com/folio-org/ui-receiving/assets/116072773/3fa8777d-e334-491d-aa02-2d54fe884ff8
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIREC-322: Add Bound items accordion in receiving

- src/ReceivingList/ExportSettingsModal/ExportSettingsModal.test.js
- src/TitleDetails/BoundItemsList/utils.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.test.js
[UIREC-322](https://folio-org.atlassian.net/browse/UIREC-322): fix pieces and item statuses from comments(only 1 and 2)
https://folio-org.atlassian.net/browse/UIREC-322?focusedCommentId=218940
And we will have a separate ticket for the 3rd option
> UIREC-322: fix pieces and item statuses

- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.test.js
- src/TitleDetails/TitleInformation/TitleInformation.test.js
- src/TitleForm/TitleForm.test.js
> UIREC-339 fix tests

- CHANGELOG.md
- src/TitleBindPieces/TitleBindPiecesConfirmationModal/TitleBindPiecesConfirmationModal.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/TitleDetails/BoundItemsList/BoundItemsList.test.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveContainer.test.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveContainer.test.js
- src/common/constants/api.js
- src/common/hooks/usePaginatedPieces/hooks/usePieceRequestsFetch.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.test.js
- src/common/hooks/usePaginatedPieces/util.js
- src/common/hooks/usePaginatedPieces/util.test.js
- src/common/hooks/useQuickReceive.js
- src/common/hooks/useQuickReceive.test.js
- src/common/hooks/useTitleHydratedPieces/useTitleHydratedPieces.js
- src/common/hooks/useTitleHydratedPieces/useTitleHydratedPieces.test.js
- src/common/utils/getHydratedPieces.js
- translations/ui-receiving/en.json
Reverts folio-org/ui-receiving#548
> Revert "UIREC-373: ECS - Use new endpoint to fetch pieces associated requests in all tenants"

- src/ReceivingList/ReceivingListContainer.js
- src/ReceivingList/utils.js
- src/ReceivingList/utils.test.js
> UIREC-339 change approach to load locations on titles list

- src/TitleDetails/BoundItemsList/hooks/useBoundItems/useBoundItems.js
- src/TitleDetails/BoundItemsList/hooks/useBoundItems/useBoundItems.test.js
> UIREC-369 fix bind pieces list

- CHANGELOG.md
- src/TitleDetails/RoutingList/RoutingList.js
> UIREC-380 Receiving app closes after closing Routing list page

- CHANGELOG.md
- src/TitleBindPieces/TitleBindPiecesConfirmationModal/TitleBindPiecesConfirmationModal.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.test.js
- src/TitleBindPieces/constants.js
- src/TitleDetails/AddPieceModal/AddPieceModal.js
- src/TitleDetails/AddPieceModal/AddPieceModal.test.js
- src/TitleDetails/constants.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- translations/ui-receiving/en.json
[UIREC-371](https://folio-org.atlassian.net/browse/UIREC-371): Improve item record behavior for items associated with receiving pieces after binding
https://github.com/user-attachments/assets/4aa798f4-402f-4ce0-b067-de03ebf22907
https://github.com/user-attachments/assets/e441d0e8-6834-4fcd-8b45-5fe8904f7f0a
https://github.com/user-attachments/assets/485d8baf-7da9-443d-9ffe-f31ba8888a6d
- …
> UIREC-371: Improve item record behavior for items associated with receiving pieces after binding

- src/Piece/PieceEdit/PieceEdit.js
UIREC-371: ECS-pass `piece.receivingTenantId` to fetch associated item
https://github.com/user-attachments/assets/33ca26ba-64d3-41f4-8980-1643d12abd28
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> UIREC-371: ECS - pass `piece.receivingTenantId` to fetch associated item

- CHANGELOG.md
- src/ReceivingList/utils.js
https://folio-org.atlassian.net/browse/UIREC-385 …
> UIREC-385 Break order lines in chunks on receiving list

- CHANGELOG.md
- package.json
Release includes https://github.com/folio-org/ui-receiving/pull/564
> Release v5.0.5

- CHANGELOG.md
- src/Piece/PieceForm/PieceFields/PieceFields.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/components/CreateItemField/CreateItemField.test.js
- src/common/components/CreateItemField/style.css
[UIREC-387](https://folio-org.atlassian.net/browse/UIREC-387): ECS: Disable Item Connected link when item is located in another tenant
https://github.com/user-attachments/assets/9e57f3ba-f0eb-434f-88dd-174865ac2650 …
> UIREC-387: ECS: Disable Item Connected link when item is located in another tenant

- CHANGELOG.md
- src/Piece/PieceForm/ItemFields/ItemFields.js
- src/Piece/PieceForm/PieceForm.test.js
- src/TitleBindPieces/TitleBindPieces.js
- src/TitleBindPieces/TitleBindPieces.test.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.test.js
- src/TitleBindPieces/constants.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/hooks/index.js
- src/common/hooks/useHoldingsAndLocations/index.js
- src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.js
- src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.test.js
[UIREC-386](https://folio-org.atlassian.net/browse/UIREC-386): ECS: Holding name should be displayed for member holdings in "Permanent location" dropdown
https://github.com/user-attachments/assets/45ea4ed9-527a-4568-9240-45c723ccf596 …
> UIREC-386: ECS: Holding name should be displayed for member holdings in "Permanent location" dropdown

- CHANGELOG.md
- src/Piece/PieceForm/PieceForm.js
- src/ReceivingList/utils.js
- src/ReceivingList/utils.test.js
- src/TitleBindPieces/TitleBindPieces.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/TitleReceive/TitleReceive.js
- src/common/constants/api.js
- src/common/constants/constants.js
- src/common/utils/index.js
- src/common/utils/setLocationValueFormMutator.js
- src/common/utils/setLocationValueFormMutator.test.js
https://folio-org.atlassian.net/browse/UIREC-389
https://folio-org.atlassian.net/browse/UIREC-391
UIREC-389: Use `/search/consortium/batch/holdings` endpoint to fetch consortium holdings by instance IDs in the central ordering mode.
UIREC-391: handle `<FieldInventory />` value changes correctly
https://github.com/user-attachments/assets/8b350c23-de19-493a-9799-79d6053b0be0
- Do PRs exist …
> UIREC-389 ECS - Optimize requests to fetch consortium holdings

- CHANGELOG.md
- src/Piece/PieceForm/PieceFields/PieceFields.js
- src/TitleReceive/TitleReceiveList.js
- src/common/components/CreateItemField/CreateItemField.js
- src/common/components/CreateItemField/CreateItemField.test.js
[UIREC-394](https://folio-org.atlassian.net/browse/UIREC-394): ECS - Disable "Create item" checkbox/link from member tenant in "Receive" full-screen form
https://github.com/user-attachments/assets/c02ea6bb-d242-41af-b041-1f736a152370
https://github.com/user-attachments/assets/b9abac84-8d1f-40b3-b951-cbef475d2136
Ideally all of the PRs involved in breaking …
> UIREC-394: ECS - Disable "Create item" checkbox/link from member tenant in "Receive" full-screen form

- src/TitleUnreceive/TitleUnreceiveContainer.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.test.js
- src/common/hooks/useTitleHydratedPieces/useTitleHydratedPieces.js
- src/common/utils/getHydratedPieces.js
- src/common/utils/getHydratedPieces.test.js
temporary solution for UAT - will be moved to BE …
> UIREC-390 tmp solution to filter pieces by tenants on client side

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- src/Piece/PieceForm/PieceFields/PieceFields.js
- src/Piece/PieceForm/PieceForm.js
- src/Piece/PieceForm/PieceForm.test.js
- src/Piece/PieceForm/PieceFormContainer.js
- src/Piece/PieceForm/PieceFormContainer.test.js
- src/ReceivingList/ExportSettingsModal/ExportSettingsModalContainer.test.js
- src/TitleBindPieces/TitleBindPieces.test.js
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/TitleForm/TitleForm.test.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveContainer.test.js
- src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.js
- src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.test.js
- src/common/utils/getHoldingLocations.js
- src/common/utils/getHoldingLocations.test.js
- test/jest/helpers/index.js
- test/jest/helpers/renderWithRouter.js
- [UIREC-393](https://folio-org.atlassian.net/browse/UIREC-393): ECS - Fix invalid reference for holding drop-down component
- `actions/upload-artifact@v2` to `actions/upload-artifact@v4` due to deprecation https://github.com/folio-org/ui-receiving/actions/runs/10715070868/job/29709994731?pr=574
https://github.com/user-attachments/assets/925b6271-0299-4178-8de4-6102024d255b
- Do PRs exist …
> UIREC-393: ECS - Fix invalid reference for holding drop-down component

- CHANGELOG.md
- src/Piece/PieceForm/PieceForm.js
- src/Piece/PieceForm/PieceForm.test.js
[UIREC-382](https://folio-org.atlassian.net/browse/UIREC-382): `Delete` and `Unreceive` buttons be disabled if pieces are bound
https://github.com/user-attachments/assets/2d690ac4-5692-4f8a-9554-0157b0f63e24
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> UIREC-382: `Delete` and `Unreceive` buttons be disabled if pieces are bound

- CHANGELOG.md
- package.json
[UIREC-396](https://folio-org.atlassian.net/browse/UIREC-396): Bump up okapi interfaces for pieces (3.1) to support a new endpoint `/orders/pieces-requests/`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> UIREC-396: Bump up okapi interfaces for `pieces` (3.1) to support a new endpoint

- src/Piece/PieceForm/PieceForm.js
- src/TitleBindPieces/TitleBindPiecesCreateItemForm/TitleBindPiecesCreateItemForm.js
- src/common/hooks/useHoldingsAndLocations/useHoldingsAndLocations.js
- src/common/utils/getHoldingLocations.js
- src/common/utils/getHoldingLocations.test.js
[UIREC-393](https://folio-org.atlassian.net/browse/UIREC-393?): fix: the newly selected locations selection issuefocusedCommentId=228905
- The issue is reported in the ticket here https://folio-org.atlassian.net/browse/UIREC-395
https://github.com/user-attachments/assets/e3f8440f-a6b9-4abb-8792-0be136054e50
Ideally all of the PRs involved in breaking …
> UIREC-393: fix: the newly selected locations selection issue (follow-up)

- src/TitleDetails/BoundItemsList/utils.js
- src/common/hooks/usePaginatedPieces/util.js
- src/common/hooks/usePaginatedPieces/util.test.js
https://folio-org.atlassian.net/browse/UIREC-388
The continuation of #575
https://github.com/user-attachments/assets/dee56340-bdfb-4906-a447-dabe8c6202b2
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> UIREC-388 Replace consortium pieces' items fetch with new endpoint

- CHANGELOG.md
- src/Piece/PieceForm/PieceForm.js
- src/Piece/PieceForm/PieceForm.test.js
Revert "UIREC-382: `Delete` and `Unreceive` buttons be disabled if pieces are bound (#578)" based on the [PO's request ](https://folio-org.atlassian.net/browse/UIREC-382?focusedCommentId=229330)the changes will not be implemented
This reverts commit eeb06c1c0027a66f600b4cf694d9eff8a89166b5.
Ideally all of the PRs involved in breaking changes would be …
> Revert "UIREC-382: `Delete` and `Unreceive` buttons be disabled if pieces are bound (#578)"

- CHANGELOG.md
- src/TitleDetails/hooks/usePiecesList/usePiecesList.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
- src/common/hooks/usePaginatedPieces/usePaginatedPieces.js
- src/common/hooks/useTitleHydratedPieces/useTitleHydratedPieces.js
- src/common/utils/getHydratedPieces.js
https://folio-org.atlassian.net/browse/UIREC-390 …
> UIREC-390 Only Display pieces on receiving title view if user affiliation(s) matches piece location affiliation

- src/common/hooks/usePaginatedPieces/util.js
https://folio-org.atlassian.net/browse/UIREC-388 …
> UIREC-388 do not pass tenantId - itemId pair in inventory/tenant-items when itemId is not defined

- src/Piece/PieceForm/PieceForm.js
[UIREC-393](https://folio-org.atlassian.net/browse/UIREC-393?): fix: the newly selected locations selection [issuefocusedCommentId=228905](https://folio-org.atlassian.net/browse/UIREC-393?focusedCommentId=229636)
https://github.com/user-attachments/assets/fe146ba7-1b0e-41de-8a38-3dbdbc283733
Ideally all of the PRs involved in breaking changes would be …
> UIREC-393: refactor: additional locations and prevent loading behavior for adding pieces

- CHANGELOG.md
- src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.js
https://folio-org.atlassian.net/browse/UIREC-399 …
> UIREC-399 Action menu should be closed after 'Save and create another' action

- package.json
> UIREC-408 inventory API version update

- CHANGELOG.md
- package.json
> UIREC-410 cleanup permissions for ui-receiving

- CHANGELOG.md
- package.json
- src/ReceivingList/ReceivingListContainer.js
> UIREC-415 Do not call mod-search viewing member titles

- CHANGELOG.md
- src/common/components/LineLocationsView/LineLocationsView.js
> UIREC-419 Do not overlap components on Edit piece page when location is long

- CHANGELOG.md
- src/TitleForm/TitleForm.js
> UIREC-420 Do not disable title submit button when form has errors

- src/TitleForm/TitleForm.js
> UIREC-420 do not fetch acq units each unit change

- CHANGELOG.md
- src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.js
- src/Piece/PieceForm/PieceFormActionButtons/PieceFormActionButtons.test.js
> UIREC-418 Disable piece actions menu only  when all actions are disabled

- CHANGELOG.md
- src/TitleDetails/BoundItemsList/hooks/useBoundItems/useBoundItems.js
- src/TitleDetails/BoundItemsList/hooks/useBoundItems/useBoundItems.test.js
[UIREC-421](https://folio-org.atlassian.net/browse/UIREC-421): ECS - Display active tenant bound items
https://github.com/user-attachments/assets/2c7c53af-54a5-470c-8ca0-73c920a3e456
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> UIREC-421: ECS - Display active tenant bound items

- src/Piece/PieceForm/PieceFormContainer.js
- src/TitleReceive/TitleReceiveContainer.js
- src/TitleReceive/TitleReceiveContainer.test.js
- src/TitleUnreceive/TitleUnreceiveContainer.js
- src/TitleUnreceive/TitleUnreceiveContainer.test.js
- src/common/components/LineLocationsView/LineLocationsView.js
- src/common/hooks/useTitleHydratedPieces/useTitleHydratedPieces.js
[UIREC-393](https://folio-org.atlassian.net/browse/UIREC-393): fix invalid reference issue for Unreceive pieces full screen page …
> UIREC-393: fix invalid reference issue for Unreceive pieces full screen page

- CHANGELOG.md
- src/TitleBindPieces/TitleBindPiecesContainer/TitleBindPiecesContainer.js
- src/TitleBindPieces/hooks/useBindPiecesMutation/useBindPiecesMutation.js
- src/TitleReceive/TitleReceiveContainer.js
- src/contexts/ReceivingSearchContext.js
https://folio-org.atlassian.net/browse/UIREC-422 …
> UIREC-422 Provide target tenant to piece mutations

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIREC-432
https://folio-org.atlassian.net/browse/UIREC-433
> UIREC-432 UIREC-433 Migrate react-intl and stripes dependencies

- src/Piece/PieceForm/ItemFields/ItemFields.js
- src/TitleReceive/TitleReceiveList.js
- src/common/hooks/useNumberGeneratorOptions/useNumberGeneratorOptions.js
PR https://github.com/folio-org/ui-receiving/pull/633 introduces an issue, that breaks `ui-receiving` app in the ECS mode.
https://github.com/user-attachments/assets/4f287beb-408e-4c5a-9472-929385fdd622
> UIREC-279 Fix number generator requests

- src/Piece/hooks/usePieceStatusChangeLog/usePieceStatusChangeLog.js
- src/common/hooks/useNumberGeneratorOptions/useNumberGeneratorOptions.js
- src/common/hooks/usePiece/usePiece.js
- src/common/hooks/useTitle/useTitle.js
> UIREC-279 fix namespaces across module

- CHANGELOG.md
- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
https://folio-org.atlassian.net/browse/UIREC-375
https://github.com/user-attachments/assets/5adec1fb-5ff4-4df7-ae5c-eca0e4d8a4e3
https://github.com/user-attachments/assets/85f180a3-f7d7-41eb-8916-e4bb53500ded
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UIREC-375 Use 'Selection' component for order status and order type filters

- src/ReceivingList/ReceivingListFilter/ReceivingListFilter.js
https://folio-org.atlassian.net/browse/UIREC-375
https://github.com/user-attachments/assets/7b716102-47e9-4cdc-82f3-f10122457a83 …
> UIREC-375 Replace Selection with Select filter

- CHANGELOG.md
- src/Piece/PieceForm/PieceForm.js
- src/common/components/CreateItemField/CreateItemField.js
https://folio-org.atlassian.net/browse/UIREC-443
https://github.com/user-attachments/assets/ca470f75-16f3-4e2f-8022-fb1f6db10eb7 …
> UIREC-443 Remove the limitation of displaying the 'Create item' checkbox by the status of a piece

- CHANGELOG.md
- package.json
Update for Split Search & Browse APIs
https://folio-org.atlassian.net/browse/UIREC-458
Update interfaces
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UIREC-458 Update for Split Search & Browse APIs

- CHANGELOG.md
- src/Piece/PieceEdit/PieceEdit.js
- src/Piece/PieceForm/PieceForm.js
- src/Piece/PieceForm/PieceForm.test.js
- src/Piece/PieceForm/PieceFormContainer.js
- src/Piece/constants.js
https://folio-org.atlassian.net/browse/UIREC-473
Use an internal form field (`nextReceivingStatus`) to keep the next status of a piece, which should be applied after an action succeeds.
https://github.com/user-attachments/assets/2cb23c08-7bae-44f1-94a7-76c5f31fe94e
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> UIREC-473 Update a piece status in the submit handler to allow user properly cancel an action
